---
title: "Rare and Endemic"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

This is an R Markdown to analysis the distribution of rare and endemic vertebrates and invertebrates in the dataset. To understand there geographic and temporal gaps. 

Table of Content: 
Mammals
Reptiles
Amphibians
Birds

```{r Download Packages}
# load packages
library(tidyverse)
library(lubridate)
library(ggplot2)
library(dplyr)
library(RColorBrewer)
```

#MAMMALS

```{r mammal data}
mam_inat <- read_csv("mammal/mam_inat.csv")

mam_chis <- read_csv("mammal/mam_chis.csv")

```

```{r mammal master}


#inat doesn't have order listed..would need to add 
mam_inat_combine <- mam_inat %>%
  rename(class="iconic_tax") %>%
  select(source, month, year, island, class, acceptedFamily, acceptedGenus, acceptedName)

#doesn't have location information!!!!
mam_chis_combine <- mam_chis %>%
  select(source, month, year, island, class, acceptedFamily, acceptedGenus, acceptedName)


mam_master = rbind(mam_inat_combine, mam_chis_combine) %>%
  # reorder the island names to show up N -> S on list
  mutate(island = fct_relevel(island, "San Miguel", "Santa Rosa", "Santa Cruz", "Anacapa", "Santa Barbara", "Santa Catalina", "San Nicolas", "San Clemente"))

```

```{r Creating a new datasheet with just endemics}
mam_end <- read_csv("mammal/mam_end.csv")

mam_end_join = inner_join(mam_master, mam_end)

```

```{r island fox}
fox = filter(mam_end_join, acceptedGenus=="Urocyon")
fox_yearrare = ggplot(fox, aes(x=year, fill=source)) + 
  geom_bar() + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=2, scales="free") 
fox_yearrare = fox_yearrare  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15)) 

fox_yearrare

ggsave(plot=fox_yearrare, filename="mammal/MammalGraphs/mam_er_fox.png", height=20, width=45, units="cm", dpi=300)

```

```{r deermouse}
mouse = filter(mam_end_join, acceptedGenus=="Peromyscus")
mouse_yearrare = ggplot(mouse, aes(x=year, fill=source)) + 
  geom_bar() + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=3, scales="free") 
mouse_yearrare = mouse_yearrare  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(n.breaks=8) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15)) 

mouse_yearrare

ggsave(plot=mouse_yearrare, filename="mammal/MammalGraphs/mam_er_deermouse.png", height=30, width=45, units="cm", dpi=300)
```

```{r skunk}
skunk = filter(mam_end_join, acceptedGenus=="Spilogale")
skunk_yearrare = ggplot(skunk, aes(x=year, fill=source)) + 
  geom_bar() + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=1, scales="free")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(n.breaks=8)

skunk_yearrare

ggsave(plot=skunk_yearrare, filename="mammal/MammalGraphs/mam_er_skunk.png", height=10, width=15, units="cm", dpi=300)
```

```{r Pacific bat}
bat1 = filter(mam_end_join, acceptedGenus=="Antrozous")
bat1_yearrare = ggplot(bat1, aes(x=year, fill=source)) + 
  geom_bar() + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=1, scales="free")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(n.breaks=8)

bat1_yearrare

ggsave(plot=bat1_yearrare, filename="mammal/MammalGraphs/mam_er_bat1.png", height=10, width=15, units="cm", dpi=300)
```

```{r other bat}
bat2 = filter(mam_end_join, acceptedGenus=="Corynorhinus")
bats = rbind(bat1, bat2) %>%
mutate(acceptedName2 = fct_relevel(acceptedName, "Corynorhinus townsendii pallescens", "Corynorhinus townsendii townsendii", "Antrozous pallidus pacificus"))
bat2_yearrare = ggplot(bat2, aes(x=year, fill=source)) + 
  geom_bar() + 
  theme_bw() + 
  labs(x="Year", y ="Number of Occurences") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=1, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1900, 1920, 1940, 1960, 1980, 2000, 2020))

bat2_yearrare

ggsave(plot=bat2_yearrare, filename="mammal/MammalGraphs/mam_er_bat2.png", height=10, width=30, units="cm", dpi=300)

# combining bats
bats_yearrare = ggplot(bats, aes(x=year, fill=source)) + 
  geom_bar() + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName2), nrow=2, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1900, 1920, 1940, 1960, 1980, 2000, 2020))

bats_yearrare

ggsave(plot=bats_yearrare, filename="mammal/MammalGraphs/mam_er_bats.png", height=20, width=30, units="cm", dpi=300)
```

```{r harvest mouse}
harv_mouse =  filter(mam_end_join, acceptedGenus=="Reithrodontomys")
harvmouse_yearrare = ggplot(harv_mouse, aes(x=year, fill=source)) + 
  geom_bar() + 
  theme_bw() + 
  labs(x="Year", y ="Number of Occurences") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=1, scales="free")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(n.breaks=8)

harvmouse_yearrare

ggsave(plot=harvmouse_yearrare, filename="mammal/MammalGraphs/mam_er_harvmouse.png", height=10, width=15, units="cm", dpi=300)
```

```{r squirrel}
squirrel = filter(mam_end_join, acceptedGenus=="Otospermophilus")
squirrel_yearrare = ggplot(mam_end_island, aes(x=year, fill=source)) + 
  geom_bar() + 
  theme_bw() + 
  labs(x="Year", y ="Number of Occurences") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=2, scales="free")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(n.breaks=8) +
theme(axis.text = element_text(size = 8), axis.title = element_text(size=12), strip.text = element_text(size=14)) 
squirrel_yearrare

ggsave(plot=squirrel_yearrare, filename="mammal/MammalGraphs/mam_er_endemic_combo.png", height=20, width=30, units="cm", dpi=300)
```

```{r shrew}
shrew= filter(mam_end_join, acceptedGenus=="Sorex")
shrew_yearrare = ggplot(shrew, aes(x=year, fill=source)) + 
  geom_bar(width=0.75) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Occurences") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=1)  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(limits=c(1890, 2020), breaks=c(1941, 1983, 1991, 2004))

shrew_yearrare

ggsave(plot=shrew_yearrare, filename="mammal/MammalGraphs/mam_er_shrew.png", height=10, width=15, units="cm", dpi=300)

#combine squirrel and shrew 
sqshrew = rbind(squirrel, shrew)
sqshrew_yearrare = ggplot(sqshrew, aes(x=year, fill=source)) + 
  geom_bar(width=0.75) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=1)  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(limits=c(1920, 2020), breaks=c(1890, 1900, 1920, 1940, 1960, 1980, 2000, 2020))

sqshrew_yearrare

ggsave(plot=sqshrew_yearrare, filename="mammal/MammalGraphs/mam_er_sqshrew.png", height=10, width=30, units="cm", dpi=300)
```

```{r taxa by island}
mam_end_island = rbind(harv_mouse, shrew, squirrel, skunk)
mam_end_islandsum <- mam_end_island %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source) %>%
  summarise(samples = sum(no_sample))

mam_end_islandsum <- na.omit(subset(mam_end_islandsum, select = c(island, samples, acceptedName, source)))
island_size = read_csv("island_size.csv")
mam_end_islandsum2 = merge(mam_end_islandsum, island_size, by="island", all.y=TRUE) 

#replaced NAs in acceptedName with one of the species so an NA graph doesn't appear, but doesn't impact other graphs at all
mam_end_islandsum2$acceptedName[is.na(mam_end_islandsum2$acceptedName)] <- "Sorex ornatus willetti"


mam_end_island_ex <- ggplot(data = mam_end_islandsum2, aes(x = samples, y = fct_rev(island), fill=source)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), ncol=2, scales="free_x") +
  labs(y ="Island", 
       x = "Number of Data Points",
       fill = "source") +
  theme_bw() +  scale_fill_brewer(palette="Dark2") + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=12), strip.text = element_text(size=14)) 
mam_end_island_ex

#4 observations in the Cal-IBIS dataset 
ggsave(plot=mam_end_island_ex, filename="mammal/MammalGraphs/mam_end_island_ex.png",  height=20, width=30, units="cm", dpi=300)
```

```{r bats island}
mam_end_island_bat 
mam_end_islandsum_bats <- bats %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName2, source) %>%
  summarise(samples = sum(no_sample))

mam_end_islandsum_bats <- na.omit(subset(mam_end_islandsum_bats, select = c(island, samples, acceptedName2, source)))
island_size = read_csv("island_size.csv")
mam_end_islandsum2_bats = merge(mam_end_islandsum_bats, island_size, by="island", all.y=TRUE) 

#replaced NAs in acceptedName with one of the species so an NA graph doesn't appear, but doesn't impact other graphs at all
mam_end_islandsum2_bats$acceptedName2[is.na(mam_end_islandsum2_bats$acceptedName2)] <- "Corynorhinus townsendii pallescens"


mam_end_island_bats <- ggplot(data = mam_end_islandsum2_bats, aes(x = samples, y = fct_rev(island), fill=source)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName2), ncol=2, scales="free_x") +
  labs(y ="Island", 
       x = "Number of Data Points",
       fill = "source") +
  theme_bw() +  scale_fill_brewer(palette="Dark2") + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=12), strip.text = element_text(size=14)) 
mam_end_island_bats

ggsave(plot=mam_end_island_bats, filename="mammal/MammalGraphs/mam_end_island_bats.png",  height=20, width=30, units="cm", dpi=300)
```

```{r fox island}

fox_end_islandsum <- fox %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source) %>%
  summarise(samples = sum(no_sample))

fox_end_islandsum <- na.omit(subset(fox_end_islandsum_, select = c(island, samples, acceptedName2, source)))
island_size = read_csv("island_size.csv")
fox_end_islandsum2 = merge(fox_end_islandsum, island_size, by="island", all.y=TRUE) 

#replaced NAs in acceptedName with one of the species so an NA graph doesn't appear, but doesn't impact other graphs at all
fox_end_islandsum2$acceptedName[is.na(fox_end_islandsum2$acceptedName)] <- "Urocyon littoralis littoralis"


fox_end_island <- ggplot(data = fox_end_islandsum2, aes(x = samples, y = fct_rev(island), fill=source)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), ncol=3, scales="free_x") +
  labs(y ="Island", 
       x = "Number of Data Points",
       fill = "source") +
  theme_bw() +  scale_fill_brewer(palette="Dark2") + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=12), strip.text = element_text(size=14)) 
fox_end_island

ggsave(plot=fox_end_island, filename="mammal/MammalGraphs/fox_end_island.png",  height=20, width=45, units="cm", dpi=300)
```

```{r mouse island}

mouse_end_islandsum <- mouse %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source) %>%
  summarise(samples = sum(no_sample))

mouse_end_islandsum <- na.omit(subset(mouse_end_islandsum_, select = c(island, samples, acceptedName2, source)))
island_size = read_csv("island_size.csv")
mouse_end_islandsum2 = merge(mouse_end_islandsum, island_size, by="island", all.y=TRUE) 

#replaced NAs in acceptedName with one of the species so an NA graph doesn't appear, but doesn't impact other graphs at all
fox_end_islandsum2$acceptedName[is.na(fox_end_islandsum2$acceptedName)] <- "Urocyon littoralis littoralis"


mouse_end_island <- ggplot(data = mouse_end_islandsum, aes(x = samples, y = fct_rev(island), fill=source)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), ncol=3, scales="free_x") +
  labs(y ="Island", 
       x = "Number of Data Points",
       fill = "source") +
  theme_bw() +  scale_fill_brewer(palette="Dark2") + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=12), strip.text = element_text(size=14)) 
mouse_end_island

ggsave(plot=mouse_end_island, filename="mammal/MammalGraphs/mouse_end_island.png", height=30, width=45, units="cm", dpi=300)
```


#
#REPTILES

```{r reptile data}
rep_inat <- read_csv("reptile/rep_inat.csv")

rep_chis <- read_csv("reptile/rep_chis.csv")

```

```{r reptile master}
#inat doesn't have order listed..would need to add 
rep_inat_combine <- rep_inat %>%
  rename(class="iconic_tax") %>%
  select(source, month, year, island, class, acceptedFamily, acceptedGenus, acceptedName, latitude, longitude)

rep_chis_combine <- rep_chis %>%
  rename(latitude = "decimalLatitude", longitude="decimalLongitude") %>%
  select(source_1, month, year, island_1, class, acceptedFamily, acceptedGenus, acceptedName, latitude, longitude) %>%
  rename(island = "island_1", source = "source_1")


rep_master = rbind(rep_inat_combine, rep_chis_combine) %>%
  # reorder the island names to show up N -> S on list
  mutate(island = fct_relevel(island, "San Miguel", "Santa Rosa", "Santa Cruz", "Anacapa", "Santa Barbara", "Santa Catalina", "San Nicolas", "San Clemente"))
```

```{r Creating a new datasheet with just endemics}
rep_end <- read_csv("endemic/rept_end.csv")

rep_end_join = inner_join(rep_master, rep_end)

#5 endemics to make graphs for, one group of two subsp

```

```{r night lizard}
nightliz = filter(rep_end_join, acceptedGenus=="Xantusia")
nightliz_yearrare = ggplot(nightliz, aes(x=year, fill=source)) + 
  geom_bar() + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=1, scales="free")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1810, 1840, 1870, 1900, 1930, 1960, 1990, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15)) 

nightliz_yearrare

ggsave(plot=nightliz_yearrare, filename="reptile/ReptileGraphs/rep_er_nightliz.png", height=10, width=30, units="cm", dpi=300)
```

```{r spiny lizard}
sceloporus = filter(rep_end_join, acceptedGenus=="Sceloporus")
sceloporus_yearrare = ggplot(sceloporus, aes(x=year, fill=source)) + 
  geom_bar() + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=1, scales="free")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15)) 

sceloporus_yearrare

ggsave(plot=sceloporus_yearrare, filename="reptile/ReptileGraphs/rep_er_sceloporus.png", height=10, width=15, units="cm", dpi=300)
```

```{r scr gopher snake}
scrgopher = filter(rep_end_join, acceptedGenus=="Pituophis")
scrgopher_yearrare = ggplot(scrgopher, aes(x=year, fill=source)) + 
  geom_bar() + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=1, scales="free")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15)) 

scrgopher_yearrare

ggsave(plot=scrgopher_yearrare, filename="reptile/ReptileGraphs/rep_er_scrgopher.png", height=10, width=15, units="cm", dpi=300)
```

```{r garter snake}
garter = filter(rep_end_join, acceptedGenus=="Thamnophis")
garter_yearrare = ggplot(garter, aes(x=year, fill=source)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=1, scales="free")  + scale_y_continuous(limits=c(0,5), expand=expansion(mult=c(0,0.05))) + scale_x_continuous(limits=c(1919, 1990), breaks=c(1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15)) 

garter_yearrare

ggsave(plot=garter_yearrare, filename="reptile/ReptileGraphs/rep_er_garter.png", height=10, width=15, units="cm", dpi=300)
```

```{r taxa by island}
rep_end_island
rep_end_islandsum <- rep_end_join %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source) %>%
  summarise(samples = sum(no_sample))

island_size = read_csv("island_size.csv")
rep_end_islandsum2 = merge(rep_end_islandsum, island_size, by="island", all.y=TRUE) 

#replaced NAs in acceptedName with one of the species so an NA graph doesn't appear, but doesn't impact other graphs at all
rep_end_islandsum2$acceptedName[is.na(rep_end_islandsum2$acceptedName)] <- "Sceloporus occidentalis becki"


rep_end_island_ex <- ggplot(data = rep_end_islandsum2, aes(x = samples, y = fct_rev(island), fill=source)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=2, scales="free_x") +
  labs(y ="Island", 
       x = "Number of Data Points",
       fill = "source") +
  theme_bw() +  scale_fill_brewer(palette="Dark2") + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=12), strip.text = element_text(size=14)) 
rep_end_island_ex

#4 observations in the Cal-IBIS dataset 
ggsave(plot=rep_end_island_ex, filename="reptile/ReptileGraphs/rep_end_island_ex.png",  height=20, width=40, units="cm", dpi=300)

```

#
#AMPHIBIANS 
```{r amphibian data}
amph_inat <- read_csv("amphibian/amph_inat.csv")

amph_chis <- read_csv("amphibian/amph_chis.csv")

```

```{r amphibian master}
#inat doesn't have order listed..would need to add 
amph_inat_combine <- amph_inat %>%
  rename(class="iconic_tax") %>%
  select(source, month, year, island, class, acceptedGenus, acceptedName, latitude, longitude)

amph_chis_combine <- amph_chis %>%
  rename(latitude = "decimalLatitude", longitude="decimalLongitude", month="month_", year="year_") %>%
  select(source_1, month, year, island_1, class, acceptedGenus, acceptedName, latitude, longitude) %>%
  rename(island = "island_1", source = "source_1")


amph_master = rbind(amph_inat_combine, amph_chis_combine) %>%
  # reorder the island names to show up N -> S on list
  mutate(island = fct_relevel(island, "San Miguel", "Santa Rosa", "Santa Cruz", "Anacapa", "Santa Barbara", "Santa Catalina", "San Nicolas", "San Clemente"))
```

```{r Creating a new datasheet with just endemics}
amph_end <- read_csv("endemic/amphib_end.csv")

amph_end_join = inner_join(amph_master, amph_end)

#1 endemic

```

```{r salamander}

salamander_yearrare = ggplot(amph_end_join, aes(x=year, fill=source)) + 
  geom_bar() + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=1, scales="free")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1800, 1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=10), strip.text = element_text(size=11)) 

salamander_yearrare

ggsave(plot=salamander_yearrare, filename="reptile/ReptileGraphs/amph_er_salamander.png", height=10, width=15, units="cm", dpi=300)

#saved in Rep folder
```

```{r salamander by island}
amph_end_islandsum <- amph_end_join %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source) %>%
  summarise(samples = sum(no_sample))


island_size = read_csv("island_size.csv")
amph_end_islandsum2 = merge(amph_end_islandsum, island_size, by="island", all.y=TRUE) 

#replaced NAs in acceptedName with one of the species so an NA graph doesn't appear, but doesn't impact other graphs at all
amph_end_islandsum2$acceptedName[is.na(amph_end_islandsum2$acceptedName)] <- "Batrachoseps pacificus"


amph_end_island_ex <- ggplot(data = amph_end_islandsum2, aes(x = samples, y = fct_rev(island), fill=source)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=1, scales="free_x") +
  labs(y ="Island", 
       x = "Number of Data Points",
       fill = "source") +
  theme_bw() +  scale_fill_brewer(palette="Dark2") + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=10), strip.text = element_text(size=11)) 

amph_end_island_ex

#into rep folder
ggsave(plot=amph_end_island_ex, filename="reptile/ReptileGraphs/amph_end_island_ex.png", height=10, width=15, units="cm", dpi=300)

```



#
#BIRDS
```{r bird data}

aves_chis = read_csv("aves/aves_chis_replacement.csv")
aves_ebird = read_csv("aves/aves_ebird2.csv")
aves_inat = read_csv("aves/aves_inat3.csv")
aves_sbmnh_obs = read_csv("aves/aves_sbmnh_obs3.csv")
aves_sbmnh_col = read_csv("aves/aves_sbmnh_col3.csv")

```

```{r bird master}
aves_inat_combine <- aves_inat %>%
  rename(class="iconic_tax", type="collectionType") %>%
  select(source, month, year, island, class, acceptedFamily, acceptedGenus, acceptedName, latitude, longitude, type, scientificName) %>%
  add_column(family= NA, genus =NA)

aves_chis_combine <- aves_chis %>%
  rename(latitude = "decimalLatitude", longitude="decimalLongitude", year="year_", month="month_", type="collectionType") %>%
  select(source, month, year, island, class, acceptedFamily, acceptedGenus, acceptedName, latitude, longitude, type, family, genus, scientificName)

aves_sbmnh_obs_combine <- aves_sbmnh_obs %>%
  rename(latitude = "decimalLatitude", longitude="decimalLongitude", type="collectionType") %>%
  select(source, month, year, island, class, acceptedFamily, acceptedGenus, acceptedName, latitude, longitude, type, family, genus, scientificName)

aves_sbmnh_col_combine <- aves_sbmnh_col %>%
  rename(latitude = "decimalLatitude", longitude="decimalLongitude", type="collectionType") %>%
  select(source, month, year, island, class, acceptedFamily, acceptedGenus, acceptedName, latitude, longitude, type, family, genus, scientificName)

aves_ebird_combine <- aves_ebird %>%
  rename(latitude = "decimalLatitude", longitude="decimalLongitude", year="year_", month="month_", type = "collection Type") %>%
  select(month, year, island, class, acceptedFamily, acceptedGenus, acceptedName, latitude, longitude, type, family, genus, scientificName) %>%
  add_column(source="EBIRD")
  
aves_master = rbind(aves_inat_combine, aves_chis_combine, aves_sbmnh_obs_combine, aves_sbmnh_col_combine, aves_ebird_combine) %>%
  # reorder the island names to show up N -> S on list
  mutate(island = fct_relevel(island, "San Miguel", "Santa Rosa", "Santa Cruz", "Anacapa", "Santa Barbara", "Santa Catalina", "San Nicolas", "San Clemente"))
```

```{r Creating a new datasheet with just endemics and rare}
aves_end <- read_csv("aves/aves_end_grouped.csv")

aves_end_join = inner_join(aves_master, aves_end) %>%
 mutate(source2 = fct_relevel(source, "Cal-IBIS", "iNaturalist", "EBIRD", "SBMNH Collections", "SBMNH Observations"))

#unique acceptedName to check all 51 are present
avesdata = unique(c(as.character(aves_end_join$acceptedName)))
avesend = unique(c(as.character(aves_end$acceptedName)))
diffaves = setdiff(avesend, avesdata)
diffaves
#Circus cyaneus and Rhynchops niger are not currently present in occurence data, synonymy issue?
# Rynhops niger, changed it csv. now onlt diff by Circus cyaneus, which I think was meant to be local C. hudsonius bc C. cyaneus is native to Eurasia, just added a new row with it to csv, check with DAK, hudsonius is syn, fixed and the issues with rare subsp fixed
```

```{r Creating endemic only graphs}
aves_endemic = filter(aves_end_join, Endemic=="X") %>%
    mutate(source2 = fct_relevel(source, "Cal-IBIS", "iNaturalist", "EBIRD", "SBMNH Collections", "SBMNH Observations"))

#temporal
aves_endemic_year = ggplot(aves_endemic, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +   scale_fill_brewer(palette = "Dark2") + facet_wrap(vars(acceptedName), nrow=4, scales="free")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_endemic_year

ggsave(plot=aves_endemic_year, filename="aves/AvesGraphs/aves_endemic_year.png", height=40, width=45, units="cm", dpi=300)
```
```{r endemic island}

aves_endemic_islandsum <- aves_endemic %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_endemic_islandsum2 <- na.omit(subset(aves_endemic_islandsum, select = c(island, samples, source2, acceptedName)))

aves_end_island <- ggplot(data = aves_endemic_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=4, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() +  scale_fill_brewer(palette="Dark2") + scale_x_continuous(expand=expansion(mult=c(0,0.5))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_end_island

ggsave(plot=aves_end_island, filename="aves/AvesGraphs/aves_endemic_island.png", height=40, width=45, units="cm", dpi=300)

```


```{r bird group A Accipitridae}
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#[1] "#1B9E77" "#D95F02" "#7570B3" "#E7298A" "#66A61E"
# different lighter green "#A6D96A
aPalette <- c("#1B9E77", "#D95F02", "#7FBC41")

aves_end_a = filter(aves_end_join, group=="a")

#temporal
aves_a_year = ggplot(aves_end_a, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") + scale_fill_manual(values=aPalette) + facet_wrap(vars(acceptedName), nrow=2, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_a_year

ggsave(plot=aves_a_year, filename="aves/AvesGraphs/aves_a_year.png", height=20, width=35, units="cm", dpi=300)
```
```{r bird A island}

aves_a_islandsum <- aves_end_a %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_a_islandsum2 <- na.omit(subset(aves_a_islandsum, select = c(island, samples, source2, acceptedName)))

aves_a_island <- ggplot(data = aves_a_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=2, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=aPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_a_island

ggsave(plot=aves_a_island, filename="aves/AvesGraphs/aves_a_island.png", height=20, width=35, units="cm", dpi=300)
```

```{r bird group B Anatidae }
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#[1] Cal-IBIS "#1B9E77" iNaturalist "#D95F02" "EBIRD #7570B3" SBMNH Col "#E7298A" SBMNH Obs "#7FBC41"
bPalette <- c("#D95F02", "#7570B3", "#7FBC41")

aves_end_b = filter(aves_end_join, group=="b")

#temporal
aves_b_year = ggplot(aves_end_b, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=bPalette) + facet_wrap(vars(acceptedName), nrow=2, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_b_year

ggsave(plot=aves_b_year, filename="aves/AvesGraphs/aves_B_year.png", height=20, width=35, units="cm", dpi=300)
```
```{r bird B island}

aves_b_islandsum <- aves_end_b %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_b_islandsum2 <- na.omit(subset(aves_b_islandsum, select = c(island, samples, source2, acceptedName)))

aves_b_island <- ggplot(data = aves_b_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=2, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=bPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_b_island

ggsave(plot=aves_b_island, filename="aves/AvesGraphs/aves_B_island.png", height=20, width=35, units="cm", dpi=300)
```

```{r bird group C Hummingbird }
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#[1] Cal-IBIS "#1B9E77" iNaturalist "#D95F02" "EBIRD #7570B3" SBMNH Col "#E7298A" SBMNH Obs "#7FBC41"
cPalette <- c("#D95F02", "#E7298A", "#7FBC41")

aves_end_c = filter(aves_end_join, group=="c")

#temporal
aves_c_year = ggplot(aves_end_c, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=cPalette) + facet_wrap(vars(acceptedName), nrow=1, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_c_year

ggsave(plot=aves_c_year, filename="aves/AvesGraphs/aves_C_year.png", height=10, width=20, units="cm", dpi=300)
```
```{r bird C island}

aves_c_islandsum <- aves_end_c %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_c_islandsum2 <- na.omit(subset(aves_c_islandsum, select = c(island, samples, source2, acceptedName)))

island_size = read_csv("island_size.csv")
aves_c_islandsum2 = merge(aves_c_islandsum, island_size, by="island", all.y=TRUE) 

#replaced NAs in acceptedName with one of the species so an NA graph doesn't appear, but doesn't impact other graphs at all
aves_c_islandsum2$acceptedName[is.na(aves_c_islandsum2$acceptedName)] <- "Selasphorus sasin sedentarius"


aves_c_island <- ggplot(data = aves_c_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=1, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=cPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_c_island

ggsave(plot=aves_c_island, filename="aves/AvesGraphs/aves_C_island.png", height=10, width=20, units="cm", dpi=300)
```

```{r bird group D Charadriiformes }
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"
dPalette <- c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#7FBC41")

aves_end_d = filter(aves_end_join, group=="d")

#temporal
aves_d_year = ggplot(aves_end_d, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=dPalette) + facet_wrap(vars(acceptedName), nrow=3, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_d_year

ggsave(plot=aves_d_year, filename="aves/AvesGraphs/aves_D_year.png", height=30, width=45, units="cm", dpi=300)
```
```{r bird D island}
aves_d_islandsum <- aves_end_d %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_d_islandsum2 <- na.omit(subset(aves_d_islandsum, select = c(island, samples, source2, acceptedName)))

aves_d_island <- ggplot(data = aves_d_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=3, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=dPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_d_island

ggsave(plot=aves_d_island, filename="aves/AvesGraphs/aves_D_island.png", height=30, width=45, units="cm", dpi=300)
```

```{r bird group E Cuckoo and Falcon.. }
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"


aves_end_e = filter(aves_end_join, group=="e")

#temporal
aves_e_year = ggplot(aves_end_e, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=dPalette) + facet_wrap(vars(acceptedName), nrow=1, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_e_year

ggsave(plot=aves_e_year, filename="aves/AvesGraphs/aves_E_year.png", height=10, width=35, units="cm", dpi=300)
```
```{r bird E island}
aves_e_islandsum <- aves_end_e %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_e_islandsum2 <- na.omit(subset(aves_e_islandsum, select = c(island, samples, source2, acceptedName)))

aves_e_island <- ggplot(data = aves_e_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=1, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=dPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_e_island

ggsave(plot=aves_e_island, filename="aves/AvesGraphs/aves_E_island.png", height=10, width=30, units="cm", dpi=300)
```

```{r bird group F Quail and Loon }
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"

aves_end_f = filter(aves_end_join, group=="f")

#temporal
aves_f_year = ggplot(aves_end_f, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=dPalette) + facet_wrap(vars(acceptedName), nrow=1, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_f_year

ggsave(plot=aves_f_year, filename="aves/AvesGraphs/aves_F_year.png", height=10, width=35, units="cm", dpi=300)
```
```{r bird F island}
aves_f_islandsum <- aves_end_f %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_f_islandsum2 <- na.omit(subset(aves_f_islandsum, select = c(island, samples, source2, acceptedName)))

aves_f_island <- ggplot(data = aves_f_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=1, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=dPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_f_island

ggsave(plot=aves_f_island, filename="aves/AvesGraphs/aves_F_island.png", height=10, width=30, units="cm", dpi=300)
```

```{r bird group G Lark, Tanager, Jay}
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"


aves_end_g = filter(aves_end_join, group=="g")

#temporal
aves_g_year = ggplot(aves_end_g, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=dPalette) + facet_wrap(vars(acceptedName), nrow=2, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_g_year

ggsave(plot=aves_g_year, filename="aves/AvesGraphs/aves_G_year.png", height=20, width=35, units="cm", dpi=300)
```
```{r bird G island}

aves_g_islandsum <- aves_end_g %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_g_islandsum2 <- na.omit(subset(aves_g_islandsum, select = c(island, samples, source2, acceptedName)))

aves_g_island <- ggplot(data = aves_g_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=2, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=dPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_g_island

ggsave(plot=aves_g_island, filename="aves/AvesGraphs/aves_G_island.png", height=20, width=35, units="cm", dpi=300)
```

```{r bird group H Sparrow and Towhee}
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"
dPalette <- c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#7FBC41")

aves_end_h = filter(aves_end_join, group=="h")

#temporal
aves_h_year = ggplot(aves_end_h, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=dPalette) + facet_wrap(vars(acceptedName), nrow=2, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_h_year

ggsave(plot=aves_h_year, filename="aves/AvesGraphs/aves_H_year.png", height=20, width=45, units="cm", dpi=300)
```
```{r bird H island}
aves_h_islandsum <- aves_end_h %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_h_islandsum2 <- na.omit(subset(aves_h_islandsum, select = c(island, samples, source2, acceptedName)))

aves_h_island <- ggplot(data = aves_h_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=2, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=dPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_h_island

ggsave(plot=aves_h_island, filename="aves/AvesGraphs/aves_H_island.png", height=20, width=45, units="cm", dpi=300)
```

```{r bird group I Martin and Bank Swallow}
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"
iPalette <- c("#D95F02", "#7570B3", "#7FBC41")

aves_end_i = filter(aves_end_join, group=="i")

#temporal
aves_i_year = ggplot(aves_end_i, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=iPalette) + facet_wrap(vars(acceptedName), nrow=1, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_i_year

ggsave(plot=aves_i_year, filename="aves/AvesGraphs/aves_I_year.png", height=10, width=35, units="cm", dpi=300)
```
```{r bird I island}
aves_i_islandsum <- aves_end_i %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_i_islandsum2 <- na.omit(subset(aves_i_islandsum, select = c(island, samples, source2, acceptedName)))

island_size = read_csv("island_size.csv")
aves_i_islandsum2 = merge(aves_i_islandsum, island_size, by="island", all.y=TRUE) 

#replaced NAs in acceptedName with one of the species so an NA graph doesn't appear, but doesn't impact other graphs at all
aves_i_islandsum2$acceptedName[is.na(aves_i_islandsum2$acceptedName)] <- "Riparia riparia"


aves_i_island <- ggplot(data = aves_i_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=1, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=iPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_i_island

ggsave(plot=aves_i_island, filename="aves/AvesGraphs/aves_I_island.png", height=10, width=35, units="cm", dpi=300)
```

```{r bird group J Blackbird}
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"
dPalette <- c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#7FBC41")

aves_end_j = filter(aves_end_join, group=="j")

#temporal
aves_j_year = ggplot(aves_end_j, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=dPalette) + facet_wrap(vars(acceptedName), nrow=1, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_j_year

ggsave(plot=aves_j_year, filename="aves/AvesGraphs/aves_J_year.png", height=10, width=35, units="cm", dpi=300)
```
```{r bird J island}
aves_j_islandsum <- aves_end_j %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_j_islandsum2 <- na.omit(subset(aves_j_islandsum, select = c(island, samples, source2, acceptedName)))

aves_j_island <- ggplot(data = aves_j_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=1, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=dPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_j_island

ggsave(plot=aves_j_island, filename="aves/AvesGraphs/aves_J_island.png", height=10, width=35, units="cm", dpi=300)
```

```{r bird group K Shrike}
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"
kPalette <- c("#D95F02", "#E7298A", "#7FBC41")

aves_end_k = filter(aves_end_join, group=="k")

#temporal
aves_k_year = ggplot(aves_end_k, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=kPalette) + facet_wrap(vars(acceptedName), nrow=1, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_k_year

ggsave(plot=aves_k_year, filename="aves/AvesGraphs/aves_K_year.png", height=10, width=20, units="cm", dpi=300)
```
```{r bird K island}
aves_k_islandsum <- aves_end_k %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_k_islandsum2 <- na.omit(subset(aves_k_islandsum, select = c(island, samples, source2, acceptedName)))

island_size = read_csv("island_size.csv")
aves_k_islandsum2 = merge(aves_k_islandsum, island_size, by="island", all.y=TRUE) 

#replaced NAs in acceptedName with one of the species so an NA graph doesn't appear, but doesn't impact other graphs at all
aves_k_islandsum2$acceptedName[is.na(aves_k_islandsum2$acceptedName)] <- "Lanius ludovicianus anthonyi"

aves_k_island <- ggplot(data = aves_k_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=1, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=iPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_k_island

ggsave(plot=aves_k_island, filename="aves/AvesGraphs/aves_K_island.png", height=10, width=20, units="cm", dpi=300)
```

```{r bird group L Chat and Warbler}
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"
lPalette <- c("#D95F02", "#7570B3", "#E7298A", "#7FBC41")

aves_end_l = filter(aves_end_join, group=="l")

#temporal
aves_l_year = ggplot(aves_end_l, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=lPalette) + facet_wrap(vars(acceptedName), nrow=2, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_l_year

ggsave(plot=aves_l_year, filename="aves/AvesGraphs/aves_L_year.png", height=20, width=35, units="cm", dpi=300)
```
```{r bird L island}
aves_l_islandsum <- aves_end_l %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_l_islandsum2 <- na.omit(subset(aves_l_islandsum, select = c(island, samples, source2, acceptedName)))

aves_l_island <- ggplot(data = aves_l_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=2, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=dPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_l_island

ggsave(plot=aves_l_island, filename="aves/AvesGraphs/aves_L_island.png", height=20, width=35, units="cm", dpi=300)
```

```{r bird group M Wren }
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"
mPalette <- c("#D95F02", "#E7298A", "#7FBC41")

aves_end_m = filter(aves_end_join, group=="m")

#temporal
aves_m_year = ggplot(aves_end_m, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=mPalette) + facet_wrap(vars(acceptedName), nrow=1, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_m_year

ggsave(plot=aves_m_year, filename="aves/AvesGraphs/aves_M_year.png", height=10, width=20, units="cm", dpi=300)
```
```{r bird M island}
aves_m_islandsum <- aves_end_m %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_m_islandsum2 <- na.omit(subset(aves_m_islandsum, select = c(island, samples, source2, acceptedName)))

island_size = read_csv("island_size.csv")
aves_m_islandsum2 = merge(aves_m_islandsum, island_size, by="island", all.y=TRUE) 

#replaced NAs in acceptedName with one of the species so an NA graph doesn't appear, but doesn't impact other graphs at all
aves_m_islandsum2$acceptedName[is.na(aves_m_islandsum2$acceptedName)] <- "Thryomanes bewickii charienturus"

aves_m_island <- ggplot(data = aves_m_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=1, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=iPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_m_island

ggsave(plot=aves_m_island, filename="aves/AvesGraphs/aves_M_island.png", height=10, width=20, units="cm", dpi=300)
```

```{r bird group N Flycatcher}
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"

aves_end_n = filter(aves_end_join, group=="n")

#temporal
aves_n_year = ggplot(aves_end_n, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=dPalette) + facet_wrap(vars(acceptedName), nrow=2, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_n_year

ggsave(plot=aves_n_year, filename="aves/AvesGraphs/aves_N_year.png", height=20, width=35, units="cm", dpi=300)
```
```{r bird N island}
aves_n_islandsum <- aves_end_n %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_n_islandsum2 <- na.omit(subset(aves_n_islandsum, select = c(island, samples, source2, acceptedName)))

aves_n_island <- ggplot(data = aves_n_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=2, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=dPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_n_island

ggsave(plot=aves_n_island, filename="aves/AvesGraphs/aves_N_island.png", height=20, width=35, units="cm", dpi=300)
```

```{r bird group O Vireo}
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"
oPalette <- c("#D95F02", "#7570B3", "#E7298A", "#7FBC41")

aves_end_o = filter(aves_end_join, group=="o")

#temporal
aves_o_year = ggplot(aves_end_o, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=oPalette) + facet_wrap(vars(acceptedName), nrow=1, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_o_year

ggsave(plot=aves_o_year, filename="aves/AvesGraphs/aves_O_year.png", height=10, width=35, units="cm", dpi=300)
```
```{r bird O island}
aves_o_islandsum <- aves_end_o %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))
aves_o_islandsum2 <- na.omit(subset(aves_o_islandsum, select = c(island, samples, source2, acceptedName)))

island_size = read_csv("island_size.csv")
aves_o_islandsum2 = merge(aves_o_islandsum, island_size, by="island", all.y=TRUE) 

#replaced NAs in acceptedName with one of the species so an NA graph doesn't appear, but doesn't impact other graphs at all
aves_o_islandsum2$acceptedName[is.na(aves_o_islandsum2$acceptedName)] <- "Vireo vicinior"

aves_o_island <- ggplot(data = aves_o_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=1, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=oPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_o_island

ggsave(plot=aves_o_island, filename="aves/AvesGraphs/aves_O_island.png", height=10, width=35, units="cm", dpi=300)
```

```{r bird group P Pelican}
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"
dPalette <- c("#1B9E77","#D95F02", "#7570B3", "#E7298A", "#7FBC41")

aves_end_p = filter(aves_end_join, group=="p")

#temporal
aves_p_year = ggplot(aves_end_p, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=dPalette) + facet_wrap(vars(acceptedName), nrow=1, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_p_year

ggsave(plot=aves_p_year, filename="aves/AvesGraphs/aves_P_year.png", height=10, width=35, units="cm", dpi=300)
```
```{r bird P island}
aves_p_islandsum <- aves_end_p %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))
aves_p_islandsum2 <- na.omit(subset(aves_p_islandsum, select = c(island, samples, source2, acceptedName)))

aves_p_island <- ggplot(data = aves_p_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=1, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=dPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_p_island

ggsave(plot=aves_p_island, filename="aves/AvesGraphs/aves_P_island.png", height=10, width=35, units="cm", dpi=300)
```

```{r bird group Q Albatross Petrel}
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"

aves_end_q = filter(aves_end_join, group=="q")

#temporal
aves_q_year = ggplot(aves_end_q, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=dPalette) + facet_wrap(vars(acceptedName), nrow=2, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_q_year

ggsave(plot=aves_q_year, filename="aves/AvesGraphs/aves_Q_year.png", height=20, width=35, units="cm", dpi=300)
```
```{r bird Q island}
aves_q_islandsum <- aves_end_q %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_q_islandsum2 <- na.omit(subset(aves_q_islandsum, select = c(island, samples, source2, acceptedName)))

aves_q_island <- ggplot(data = aves_q_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=2, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=dPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_q_island

ggsave(plot=aves_q_island, filename="aves/AvesGraphs/aves_Q_island.png", height=20, width=35, units="cm", dpi=300)
```

```{r bird group R Owl}
#brewer.pal(5, name="Dark2") Color codes for the brewer colors, need 1, 2 and 4 for this one
#Cal-IBIS "#1B9E77"            iNaturalist "#D95F02"            EBIRD #7570B3"
#SBMNH Col "#E7298A"            SBMNH Obs "#7FBC41"


aves_end_r = filter(aves_end_join, group=="r")

#temporal
aves_r_year = ggplot(aves_end_r, aes(x=year, fill=source2)) + 
  geom_bar(width=0.5) + 
  theme_bw() + 
  labs(x="Year", y ="Number of Data Points", fill="source") +  scale_fill_manual(values=dPalette) + facet_wrap(vars(acceptedName), nrow=2, scales="free_y")  + scale_y_continuous(expand=expansion(mult=c(0,0.05))) + scale_x_continuous(breaks=c(1820, 1840, 1860, 1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020)) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 
aves_r_year

ggsave(plot=aves_r_year, filename="aves/AvesGraphs/aves_R_year.png", height=20, width=35, units="cm", dpi=300)
```
```{r bird R island}
aves_r_islandsum <- aves_end_r %>%
  mutate(no_sample = 1) %>%
  group_by(island, acceptedName, source2) %>%
  summarise(samples = sum(no_sample))

aves_r_islandsum2 <- na.omit(subset(aves_r_islandsum, select = c(island, samples, source2, acceptedName)))

aves_r_island <- ggplot(data = aves_r_islandsum2, aes(x = samples, y = fct_rev(island), fill=source2)) + geom_bar(stat = "identity") + facet_wrap(vars(acceptedName), nrow=2, scales="free_x") +
  labs(y ="Island",  x = "Number of Data Points", fill = "source") + theme_bw() + scale_fill_manual(values=dPalette) + scale_x_continuous(expand=expansion(mult=c(0,0.05))) + theme(axis.text = element_text(size = 8), axis.title = element_text(size=15), strip.text = element_text(size=14), legend.text = element_text(size=12)) 

aves_r_island

ggsave(plot=aves_r_island, filename="aves/AvesGraphs/aves_R_island.png", height=20, width=35, units="cm", dpi=300)
```
