---
title: "PlantSynonomy_Families"
author: "Josie Lesage"
date: "5/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
library(tidyverse)

```

# Update family names for Gap Analysis species
The goal of this R markdown is to add updated family names to the plant list for the Islands Gap Analysis.


```{r import and tidy data}

# the 'master' data
setwd('~/Desktop')

master_list <- read.csv("PlantFamilies.csv") 
  # remove accepted name column
master_list <- subset(master_list, select = -AcceptedName) 
    # rename "APG Family" column to "family_updated", make "Genus" column name lowercase
master_list <-  rename(master_list, family_updated = "APGFamily", genus = Genus)
  # collapse extra rows
master_list <- distinct(master_list, genus, family_updated) 

# the data we're working with
gap_data <- read.csv("GapAnalysis_Plants.csv") 

```

This is the code to join the two datasets. It basically treats the "left hand" data as the primary data, and searches for the appropriate match on the right hand side.

```{r add new family to gap data}

gap_data_families <- left_join(gap_data, master_list, by = "genus", ) 

```

```{r save new file}

write_csv(gap_data_families, "GapAnalysis_NewFamilies.csv", col_names = TRUE)

```

